// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BottomModalController from "./bottom_modal_controller"
application.register("bottom-modal", BottomModalController)

import DirectionController from "./direction_controller"
application.register("direction", DirectionController)

import DirectionToggleController from "./direction_toggle_controller"
application.register("direction-toggle", DirectionToggleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
